definitions:
  errcode.Error:
    type: object
  model.TagSwagger:
    type: object
  validate.CreateArticleRequest:
    properties:
      content:
        type: string
      cover_img_url:
        type: string
      created_by:
        type: string
      desc:
        type: string
      state:
        type: integer
      tag_ids:
        items:
          type: integer
        type: array
      title:
        type: string
    required:
    - created_by
    - title
    type: object
  validate.CreateTagRequest:
    properties:
      created_by:
        type: string
      name:
        type: string
      state:
        type: integer
    required:
    - created_by
    type: object
  validate.GetAuthRequest:
    properties:
      app_key:
        description: https://github.com/gin-gonic/gin#model-binding-and-validation
        type: string
      app_secret:
        type: string
    required:
    - app_key
    - app_secret
    type: object
  validate.UpdateTagRequest:
    properties:
      id:
        type: integer
      modified_by:
        type: string
      name:
        type: string
      state:
        type: integer
    required:
    - id
    - modified_by
    type: object
info:
  contact: {}
  description: 'Go 语言编程之旅: 一起用 Go 做项目'
  termsOfService: https://github.com/ChrisLeejing/go-programming-tour-book-exercise
  title: 博客系统
  version: v1.0
paths:
  /api/v1/articles:
    post:
      parameters:
      - description: JWT Token
        in: header
        name: token
        required: true
        type: string
      - description: CreateArticleRequest
        in: body
        name: CreateArticleRequest
        required: true
        schema:
          $ref: '#/definitions/validate.CreateArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 新增文章
      tags:
      - Article 文章
  /api/v1/tags:
    get:
      parameters:
      - description: JWT Token
        in: header
        name: token
        required: true
        type: string
      - description: 标签名称
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 获取多个标签
      tags:
      - Tag 标签
    post:
      parameters:
      - description: JWT Token
        in: header
        name: token
        required: true
        type: string
      - description: CreateTagRequest
        in: body
        name: CreateTagRequest
        required: true
        schema:
          $ref: '#/definitions/validate.CreateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 新增标签
      tags:
      - Tag 标签
  /api/v1/tags/{id}:
    delete:
      parameters:
      - description: JWT Token
        in: header
        name: token
        required: true
        type: string
      - description: 标签 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 删除标签
      tags:
      - Tag 标签
    get:
      parameters:
      - description: JWT Token
        in: header
        name: token
        required: true
        type: string
      - description: 标签 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 获取标签
      tags:
      - Tag 标签
    put:
      parameters:
      - description: JWT Token
        in: header
        name: token
        required: true
        type: string
      - description: UpdateTagRequest
        in: body
        name: UpdateTagRequest
        required: true
        schema:
          $ref: '#/definitions/validate.UpdateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            items:
              $ref: '#/definitions/model.TagSwagger'
            type: array
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 更新标签
      tags:
      - Tag 标签
  /auth:
    post:
      parameters:
      - description: GetAuthRequest
        in: body
        name: GetAuthRequest
        required: true
        schema:
          $ref: '#/definitions/validate.GetAuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 获取认证token
      tags:
      - Token 鉴权
  /upload/file:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 文件类型
        in: formData
        name: type
        required: true
        type: integer
      - description: file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
      summary: 文件上传
      tags:
      - File 文件
swagger: "2.0"
